serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'ikip-prometheus-aggregator'
        metrics_path: '/'
        static_configs:
          - targets: ['ikip-prometheus-aggregator:8000']
