serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'ikip-prometheus-aggregator'
        metrics_path: '/'
        static_configs:
          - targets: ['ikip-prometheus-aggregator:8000']
      - job_name: 'ipso580g91'
        static_configs:
          - targets: ['10.11.0.107:9100']
      - job_name: 'ipso380g90'
        static_configs:
          - targets: ['10.10.0.64:9100']
      - job_name: 'ipso380gx'
        static_configs:
          - targets: ['192.168.51.101:9100']
